version: "3.3"
services:
  unpub:
    image: <unpub image name>
    container_name: unpub
    restart: always
    ports:
      - 4000:4000
    volumes:
      - ~/.unpub-packages:/app/unpub-packages
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: unpub_mongo
    restart: always
    volumes:
      - ~/.unpub_mongo:/data/db
